postgis:
  build: postgis
  hostname: postgis
  volumes:
  - ./postgres_data:/var/lib/postgresql
geoserver:
  image: kartoza/geoserver
  hostname: geoserver
  links:
  - postgis:postgis
  volumes:
  - ./geoserver_data:/opt/geoserver/data_dir
