postgis:
  image: mdillon/postgis:9.6-alpine
  environment:
  - POSTGRES_PASSWORD=postgres
  hostname: postgis
  ports:
  - "5432:5432"
  volumes:
  - ./postgis:/tmp/postgis
geoserver:
  image: appliedis/geoserver:2.11.0
  environment:
  - ENABLE_CORS=true
  hostname: geoserver
  ports:
  - "80:8080"
  links:
  - postgis:postgis
  volumes:
  - ./geoserver_data:/etc/geoserver
  - ./geoserver:/tmp/geoserver
